version: "3"
services:
  composer:
    image: composer:2.0
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    command: cp .env.example .env && composer install

  php:
    build: ./docker/php
    container_name: php_cli
    volumes:
      - ./www:/var/www
      - ./docker/php/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
