version: "3"
services:
  php:
    build: ./docker/php
    container_name: php_cli
    volumes:
      - ./www:/var/www
      - ./docker/php/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
